# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badge',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
