# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20171205_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='created_at',
        ),
    ]
