# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_user_img_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
    ]
