# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 08:23
from __future__ import unicode_literals

from django.db import migrations
import utils.custom_image_filed


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20171214_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=utils.custom_image_filed.DefaultStaticImageField(upload_to='user'),
        ),
    ]
