# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_user_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badge',
            field=models.IntegerField(default=0),
        ),
    ]
