# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Explog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Explog
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'ParallaxHeader', '~> 2.0.0'
  pod 'AlamofireImage', '~> 3.3'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.2'


end
