# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 03:29
from __future__ import unicode_literals

from django.db import migrations
import utils.custom_image_filed


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=utils.custom_image_filed.DefaultStaticPostImageField(blank=True, upload_to='media'),
        ),
    ]
