# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import utils.custom_image_filed


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttext',
            name='type',
            field=models.CharField(choices=[('b', 'basic'), ('h', 'highlight')], default='b', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=utils.custom_image_filed.DefaultStaticPostImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='postreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
