# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20171229_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttext',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]