# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20171215_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
