# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20171130_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPhoto',
            new_name='Photos',
        ),
    ]
