# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20171130_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='test',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subpost',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
