# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20171201_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
