# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20171201_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='test',
        ),
    ]
