# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0008_photos_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2017-11-28T02:01:00+09:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='subpost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.SubPost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
