# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20171201_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='author',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='post',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='subpost',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='updated_at',
        ),
    ]
